[package]
name = "hamletAnalysis"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.21.2"
dioxus = "0.3.2"
dioxus-web = "0.3.2"
