name: Deployment

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  deployment:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    #credits to LyonSyonll
    - name: Setup Rust Toolchain
      uses: actions-rs/toolchain@v1.0.6
      with:
        toolchain: stable
        target: wasm32-unknown-unknown
        
    - name: Wasm-Bidgen upade
      run: cargo update -p wasm-bindgen --precise 0.2.87
        
    - name: Rust Cache
      uses: Swatinem/rust-cache@v2.2.1
      with:
        cache-on-failure: true
      
    - name: Setup Dioxus Cli
      run: cargo install dioxus-cli
      
    - name: Setup TailwindCSS Cli
      run: npm -g install tailwindcss
      
  #  - name: Run TailwindCSS Compiler
  #    run: npx tailwind -c tailwind.config.js -o src/index.css --minify
      
    - name: Run Dioxus
      run: dioxus build --release
      
    - name: Upload
      uses: actions/upload-pages-artifact@v1.0.4
      with: 
        path: dist

    - id: deploy
      name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v1
      with:
        token: ${{ github.token }}
